### ISSUE TITLE
Z̵̹͈̻̗̱͇̳̠͔͈͚͍͇̬̮̠̤̹͙͑̔͐̓͛ͬ͒ͮ̌̅̽̅̃ͩͣ͊ͬ̚͠͡h̶̨̙̩͕ͫ̃̍ͨͨͣ͐̿ͥͣ͂̄̅ͭͪ̋ͬ̈́̏͢͝͠ͅơ̛̪̩͖̙̖̜̤̺̹̘̺̹̫̞̳̭̻̎ͧ͆̃̀̕͝d̢̎͐ͯ̆̓ͬͪ̑͏̫̰̣̳̦̙̯̮͉̥͇̩̝̺x̧̣͕͕̺̝͎͉̰̺̪̥͓̝͐͊ͩ̕͢i̷̓̈́̾̀͛́̈́̓ͪͧ̈́̚̕̕͟҉̜̮̫̜̯̟̞̝͓͈͓͎̦̺g̸͈̖̘̜͎̺̭̠̞̬͓͓͎̜̘ͫ̌͊ͬ̇̇̈́̓͋̀̚͟ȟ̨̭͈͉̼͖̬̖̖̗͙͓̫̂̋̅͐̇͒́͗ͪͤͦ̽͜

### ISSUE THREAD

**Issue by Hydro7** [andrewlalis/TengwarTranslator#1]
The details of my life are quite inconsequential... very well, where do I begin? My father was a relentlessly self-improving boulangerie owner from Belgium with low grade narcolepsy and a penchant for buggery. My mother was a fifteen year old French prostitute named Chloe with webbed feet. My father would womanize, he would drink. He would make outrageous claims like he invented the question mark. Sometimes he would accuse chestnuts of being lazy. The sort of general malaise that only the genius possess and the insane lament. My childhood was typical. Summers in Rangoon, luge lessons. In the spring we'd make meat helmets. When I was insolent I was placed in a burlap bag and beaten with reeds- pretty standard really. At the age of twelve I received my first scribe. At the age of fourteen a Zoroastrian named Vilma ritualistically shaved my testicles. There really is nothing like a shorn scrotum... it's breathtaking- I highly suggest you try it.

**Comment by andrewlalis** [comment]
What the fuck
